import { NextRequest, NextResponse } from 'next/server'

// Dados mockados para demonstração - 3 áudios para cada tipo
const MOCK_AUDIOS = [
  // Locução (3 áudios)
  {
    id: 'locucao-1',
    title: 'Locução Institucional 1',
    description: 'Narração profissional para vídeo institucional com voz clara e adequada.',
    audioUrl: '/audio/aud1.mp3',
    type: 'Locução',
    client: 'Cliente Demo',
    duration: '02:30',
    coverImage: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'locucao-2',
    title: 'Locução Institucional 2',
    description: 'Narração para treinamento corporativo com tom profissional.',
    audioUrl: '/audio/aud1.mp3',
    type: 'Locução',
    client: 'Cliente Demo',
    duration: '01:45',
    coverImage: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'locucao-3',
    title: 'Locução Institucional 3',
    description: 'Narração para material educacional com voz adequada ao público.',
    audioUrl: '/audio/aud1.mp3',
    type: 'Locução',
    client: 'Cliente Demo',
    duration: '03:15',
    coverImage: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Spot Publicitário (3 áudios)
  {
    id: 'spot-1',
    title: 'Spot Publicitário 1',
    description: 'Spot publicitário para rádio com trilha sonora personalizada.',
    audioUrl: '/audio/aud1.mp3',
    type: 'Spot Publicitário',
    client: 'Cliente Demo',
    duration: '00:30',
    coverImage: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'spot-2',
    title: 'Spot Publicitário 2',
    description: 'Spot para TV e mídias digitais com roteiro criativo.',
    audioUrl: '/audio/aud1.mp3',
    type: 'Spot Publicitário',
    client: 'Cliente Demo',
    duration: '00:45',
    coverImage: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'spot-3',
    title: 'Spot Publicitário 3',
    description: 'Spot publicitário de impacto com produção de alta qualidade.',
    audioUrl: '/audio/aud1.mp3',
    type: 'Spot Publicitário',
    client: 'Cliente Demo',
    duration: '01:00',
    coverImage: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Produção de Áudio (3 áudios)
  {
    id: 'producao-1',
    title: 'Produção de Áudio 1',
    description: 'Produção de áudio profissional com qualidade superior.',
    audioUrl: '/audio/aud1.mp3',
    type: 'Produção de Áudio',
    client: 'Cliente Demo',
    duration: '02:30',
    coverImage: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'producao-2',
    title: 'Produção de Áudio 2',
    description: 'Produção completa com edição e mixagem profissional.',
    audioUrl: '/audio/aud1.mp3',
    type: 'Produção de Áudio',
    client: 'Cliente Demo',
    duration: '03:20',
    coverImage: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'producao-3',
    title: 'Produção de Áudio 3',
    description: 'Produção de áudio com masterização de alta qualidade.',
    audioUrl: '/audio/aud1.mp3',
    type: 'Produção de Áudio',
    client: 'Cliente Demo',
    duration: '02:15',
    coverImage: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Dublagem (3 áudios)
  {
    id: 'dublagem-1',
    title: 'Dublagem 1',
    description: 'Dublagem profissional para vídeo com sincronização perfeita.',
    audioUrl: '/audio/aud1.mp3',
    type: 'Dublagem',
    client: 'Cliente Demo',
    duration: '04:00',
    coverImage: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'dublagem-2',
    title: 'Dublagem 2',
    description: 'Dublagem para animação mantendo naturalidade e expressividade.',
    audioUrl: '/audio/aud1.mp3',
    type: 'Dublagem',
    client: 'Cliente Demo',
    duration: '03:30',
    coverImage: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'dublagem-3',
    title: 'Dublagem 3',
    description: 'Dublagem completa para conteúdo audiovisual.',
    audioUrl: '/audio/aud1.mp3',
    type: 'Dublagem',
    client: 'Cliente Demo',
    duration: '05:15',
    coverImage: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Narração (3 áudios)
  {
    id: 'narracao-1',
    title: 'Narração 1',
    description: 'Narração profissional para documentário com voz adequada.',
    audioUrl: '/audio/aud1.mp3',
    type: 'Narração',
    client: 'Cliente Demo',
    duration: '06:00',
    coverImage: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'narracao-2',
    title: 'Narração 2',
    description: 'Narração para conteúdo educacional com tom claro.',
    audioUrl: '/audio/aud1.mp3',
    type: 'Narração',
    client: 'Cliente Demo',
    duration: '04:30',
    coverImage: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'narracao-3',
    title: 'Narração 3',
    description: 'Narração especializada com edição profissional.',
    audioUrl: '/audio/aud1.mp3',
    type: 'Narração',
    client: 'Cliente Demo',
    duration: '05:45',
    coverImage: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Podcast (3 áudios)
  {
    id: 'podcast-1',
    title: 'Podcast 1',
    description: 'Episódio de podcast com produção completa e qualidade profissional.',
    audioUrl: '/audio/aud1.mp3',
    type: 'Podcast',
    client: 'Cliente Demo',
    duration: '30:00',
    coverImage: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'podcast-2',
    title: 'Podcast 2',
    description: 'Podcast com edição e mixagem profissional.',
    audioUrl: '/audio/aud1.mp3',
    type: 'Podcast',
    client: 'Cliente Demo',
    duration: '25:30',
    coverImage: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'podcast-3',
    title: 'Podcast 3',
    description: 'Episódio de podcast com trilha sonora e efeitos.',
    audioUrl: '/audio/aud1.mp3',
    type: 'Podcast',
    client: 'Cliente Demo',
    duration: '35:15',
    coverImage: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // E-book Narrado (3 áudios)
  {
    id: 'ebook-1',
    title: 'E-book Narrado 1',
    description: 'E-book narrado com voz profissional e edição de alta qualidade.',
    audioUrl: '/audio/aud1.mp3',
    type: 'E-book Narrado',
    client: 'Cliente Demo',
    duration: '45:00',
    coverImage: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ebook-2',
    title: 'E-book Narrado 2',
    description: 'Audiolivro completo com narração envolvente.',
    audioUrl: '/audio/aud1.mp3',
    type: 'E-book Narrado',
    client: 'Cliente Demo',
    duration: '50:30',
    coverImage: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ebook-3',
    title: 'E-book Narrado 3',
    description: 'E-book narrado com produção profissional e qualidade superior.',
    audioUrl: '/audio/aud1.mp3',
    type: 'E-book Narrado',
    client: 'Cliente Demo',
    duration: '40:15',
    coverImage: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

// GET - Listar todos os áudios (apenas dados mockados)
export async function GET() {
  console.log('[API] Usando dados mockados para áudios')
  return NextResponse.json(MOCK_AUDIOS)
}

// POST - Criar novo áudio (não disponível em modo demonstração)
export async function POST(request: NextRequest) {
  return NextResponse.json(
    { error: 'Criação de áudios não disponível em modo demonstração' },
    { status: 501 }
  )
}
